import React from 'react'
import Head from "next/head";

function _Head() {
  return (
    <div>
      <Head>
        <title>Weteck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weteck.png" />
      </Head>
    </div>
  )
}

export default _Head
